framework/users/views.py
from flask import Blueprint, current_app, render_template,request, flash,\
           session, redirect, url_for

from flask.ext.security import LoginForm, current_user, login_required, \
    login_user, logout_user
    
from flask.ext.security.decorators import anonymous_user_required
from flask.ext.security.utils import get_post_login_redirect, encrypt_password

from social.utils import config_value, get_provider_or_404
from social.views import connect_handler
from forms import RegisterForm

#from ..core import security, social

from ..decorators import route
from .models import User

bp = Blueprint('user', __name__, url_prefix="/user")


@bp.route('/')
def index():
    return redirect('/')


@bp.route('/login', methods=['GET', 'POST'])
@anonymous_user_required
def login():
    if current_user.is_authenticated():
        return redirect(request.referrer or '/')
    
    form = LoginForm()

    if form.validate_on_submit():
        login_user(form.user, remember=form.remember.data)
        return redirect(get_post_login_redirect())

        

    return render_template('security/login.html', 
                                active_nav_band = "Login",
                                form=form)
    
@route(bp, '/logout')
def logout():
    """View function which handles a logout request."""

    if current_user.is_authenticated():
        logout_user()

    return redirect(request.args.get('next', None) or
                                url_for('user.index'))


@bp.route('/register', methods=['GET', 'POST'])
@bp.route('/register/<provider_id>', methods=['GET', 'POST'])
@anonymous_user_required
def register(provider_id=None):
    if current_user.is_authenticated():
        return redirect(request.referrer or '/')

    form = RegisterForm()

    if provider_id:
        provider = get_provider_or_404(provider_id)
        connection_values = session.get('failed_login_connection', None)
    else:
        provider = None
        connection_values = None

    if form.validate_on_submit():
        ds = current_app.extensions['security'].datastore
        user = ds.create_user(email=form.email.data, 
                                  password=encrypt_password(form.password.data))
        ds.commit()

        # See if there was an attempted social login prior to registering
        # and if so use the provider connect_handler to save a connection
        connection_values = session.pop('failed_login_connection', None)

        if connection_values:
            connection_values['user_id'] = user.id
            connect_handler(connection_values, provider)

        if login_user(user):
            ds.commit()
            flash('Account created successfully', 'info')
            return redirect(url_for('user.profile'))

        return render_template('thanks.html', user=user)

    login_failed = int(request.args.get('login_failed', 0))

    return render_template('security/register.html',
                           active_nav_band = "Register",
                           form=form,
                           provider=provider,
                           login_failed=login_failed,
                           connection_values=connection_values)


@route(bp, '/profile')
def profile():
    return render_template('profile.html',
        twitter_conn=current_app.extensions['social'].twitter.get_connection(),
        facebook_conn=current_app.extensions['social'].facebook.get_connection(),
        #github_conn=current_app.extensions['social'].github.get_connection()
        )



@route(bp, '/profile/<provider_id>/post', methods=['POST'])
def social_post(provider_id):
    message = request.form.get('message', None)

    if message:
        provider = get_provider_or_404(provider_id)
        api = provider.get_api()

        if provider_id == 'twitter':
            display_name = 'Twitter'
            api.PostUpdate(message)
        if provider_id == 'facebook':
            display_name = 'Facebook'
            api.put_object("me", "feed", message=message)

        flash('Message posted to %s: %s' % (display_name, message), 'info')

    return redirect(url_for('userprofile'))


@route(bp, '/admin')
def admin():
    users = User.query.all()
    return render_template('admin.html', users=users)


@route(bp, '/admin/users/<user_id>', methods=['DELETE'])
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    flash('User deleted successfully', 'info')
    return redirect(url_for('admin'))

templates/_macros.html
{# Renders field for bootstrap 3 standards.
 
    Params:
        field - WTForm field
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_
 
    Example usage:
        {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
#}
{% macro render_field(field, label_visible=true) -%}
 
    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if (field.type != 'HiddenField' and field.type !='CSRFTokenField' and label_visible) %}
            <label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}
 
{# Renders checkbox fields since they are represented differently in bootstrap
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_
 
    Example usage:
        {{ macros.render_checkbox_field(form.remember_me) }}
 #}
{% macro render_checkbox_field(field) -%}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
{%- endmacro %}
 
{# Renders radio field
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_
 
    Example usage:
        {{ macros.render_radio_field(form.answers) }}
 #}
{% macro render_radio_field(field) -%}
    {% for value, label, _ in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}
 
{# Renders WTForm in bootstrap way. There are two ways to call function:
     - as macros: it will render all field forms using cycle to iterate over them
     - as call: it will insert form fields as you specify:
     e.g. {% call macros.render_form(form, action_url=url_for('login_view'), action_text='Login',
                                        class_='login-form') %}
                {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
                {{ macros.render_field(form.password, placeholder='Input password', type='password') }}
                {{ macros.render_checkbox_field(form.remember_me, type='checkbox') }}
            {% endcall %}
 
     Params:
        form - WTForm class
        action_url - url where to submit this form
        action_text - text of submit button
        class_ - sets a class for form
    #}
{% macro render_form(form, action_url='', action_text='Submit', class_='', btn_class='btn btn-default') -%}
    <form method="POST" action="{{ action_url }}" role="form" class="{{ class_ }}">
        {{ form.hidden_tag() if form.hidden_tag }}
        {% if caller %}
            {{ caller() }}
        {% else %}
            {% for f in form %}
                {% if f.type == 'BooleanField' %}
                    {{ render_checkbox_field(f) }}
                {% elif f.type == 'RadioField' %}
                    {{ render_radio_field(f) }}
                {% elif f.type == 'SubmitField' %}
                    {# Skip submit field for now#}
                {% else %}
                    {{ render_field(f) }}
                {% endif %}
            {% endfor %}
        {% endif %}
        <button type="submit" class="{{ btn_class }}">{{ action_text }} </button>
    </form>
{%- endmacro %}

templates/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
	  <div class="row">
	    <div class="span8 offset2">
		  {% for category, message in messages %}
		  <div class="alert alert-{{ category }}">
		    <a class="close" data-dismiss="alert">×</a>
		    {{ message }}
		  </div>
		  {% endfor %}
	    </div>
	  </div>
  {% endif %}
{%- endwith %}

templates/_nav.html
<div class="navbar-wrapper">
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Social Site Example: After School Heaven</a>
	    </div>
	    
	    <div class="navbar-collapse collapse">
	      <ul class="nav navbar-nav">
	        <li class="{% if 'Home' == active_nav_band %}active{% endif %}"><a href="{{ url_for('index') }}">Home</a></li>
	        {%- if current_user.is_authenticated() -%}
	        <li class="{% if 'Profile' == active_nav_band %}active{% endif %}"><a href="{{ url_for('user.profile') }}">Profile</a></li>
	        <li ><a href="{{ url_for('user.logout') }}">Log out</a></li>
	        {%- else -%}
	        <li class="{% if 'Login' == active_nav_band %}active{% endif %}"><a href="{{ url_for('user.login') }}">Log in</a></li>
	        <li class="{% if 'Register' == active_nav_band %}active{% endif %}"><a href="{{ url_for('user.register') }}">Register</a></li>
	        {%- endif -%}
	      </ul>
	      <ul class="nav navbar-nav navbar-right github">
	        <li><iframe src="http://ghbtns.com/github-btn.html?user=tonytan4ever&type=follow"
	  allowtransparency="true" frameborder="0" scrolling="0" width="143px" height="20px"></iframe></li>
	      </ul>
	    </div>
	  </div>
	</nav>
</div>

templates/admin.html
{% extends '/layouts/boilerplate.html' %}

{% block body_class %}admin admin-index{% endblock %}

{% block layout %}
<div class="page-header">
  <h1>Admin</h1>
</div>

<h2>{{ users|length }} Users</h2>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Last Login</th>
      <th>Current Login</th>
      <th>Login Count</th>
      <th>Connections</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  {% for u in users %}
    <tr>
      <td>{{ u.email }}</td>
      <td>{{ u.last_login_at }}</td>
      <td>{{ u.current_login_at }}</td>
      <td>{{ u.login_count }}</td>
      <td>
      	{% for c in u.connections %}
      	  {{ c.provider_id }}{% if not loop.last %}, {% endif %}
      	{% endfor %}
      </td>
      <td>
        <form action="{{ url_for('delete_user', user_id=u.id) }}?__METHOD_OVERRIDE__=DELETE" method="POST">
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/index.html
{% extends '/layouts/boilerplate.html' %}

{% block body_class %}main main-index{% endblock %}

{% set page_title = "Home" %}

{% block layout %}
  <div class="page-header">
    <h1>Welcome</h1>
    <p>
      This site illustrates the functionality provided by the <strong>Flask-Social</strong>
      extension for <strong>Flask</strong>.
    </p>
    <p>So far <strong>{{ total_users }}</strong> people have tried this site.</p>
    <p>
      <a class="btn btn-primary btn-large" href="http://packages.python.org/Flask-Social"><i class="icon-list-alt icon-white"></i> Flask-Social Documentation</a>
      <a class="btn btn-primary btn-large" href="http://packages.python.org/Flask-Security"><i class="icon-list-alt icon-white"></i> Flask-Security Documentation</a>
      <a class="btn btn-primary btn-large" href="http://flask.pocoo.org"><i class="icon-info-sign icon-white"></i> Lean more about Flask</a>
    </p>
  </div>
  <!--  <div class="row">
    <div class="span4">
      <div class="well repo-info">
        <h2>Flask-Security</h2>
        <ul class="repo-actions">
          <li>
            <iframe src="http://ghbtns.com/github-btn.html?user=mattupstate&repo=flask-security&type=watch&count=true&size=large"
                    allowtransparency="true" frameborder="0" scrolling="0" width="130px" height="30px"></iframe>
          </li>
           <li>
            <iframe src="http://ghbtns.com/github-btn.html?user=mattupstate&repo=flask-security&type=fork&count=true&size=large"
                    allowtransparency="true" frameborder="0" scrolling="0" width="120px" height="30px"></iframe></p>
          </li> 
        </ul>
      </div>
    </div>
    <div class="span4">
      <div class="well repo-info">
        <h2>Flask-Social</h2>
        <ul class="repo-actions">
          <li>
            <iframe src="http://ghbtns.com/github-btn.html?user=mattupstate&repo=flask-social&type=watch&count=true&size=large"
                    allowtransparency="true" frameborder="0" scrolling="0" width="130px" height="30px"></iframe>
          </li>
          <li>
            <iframe src="http://ghbtns.com/github-btn.html?user=mattupstate&repo=flask-social&type=fork&count=true&size=large"
                    allowtransparency="true" frameborder="0" scrolling="0" width="120px" height="30px"></iframe></p>
          </li> 
        </ul>
      </div>
    </div>
    <div class="span4">
      <div class="well repo-info">
        <h2>This Website</h2>
        <ul class="repo-actions">
          <li>
            <iframe src="http://ghbtns.com/github-btn.html?user=mattupstate&repo=flask-social-example&type=watch&count=true&size=large"
                    allowtransparency="true" frameborder="0" scrolling="0" width="130px" height="30px"></iframe>
          </li>
           <li>
            <iframe src="http://ghbtns.com/github-btn.html?user=mattupstate&repo=flask-social-example&type=fork&count=true&size=large"
                    allowtransparency="true" frameborder="0" scrolling="0" width="120px" height="30px"></iframe></p>
          </li> 
        </ul>
      </div>
    </div>
  </div>
  -->
  <div class="row">
    <div class="span10 offset1">
      <p>Flask-Social is an extension for the wonderful Python web framework, <a href="http://flask.pocoo.org">Flask</a>. It aims to add simple OAuth provider integration to your application. It is dependent on the <a href="http://packages.python.org/Flask-Security">Flask-Security</a> extension which provides simple user management. This website serves as an example of how to use both extensions effectively.</p>
      <p>Essentially, Flask-Social sets up endpoints for your app to make it easy for you to let your users connect and/or login using Facebook and Twitter. Flask-Social persists the connection information and allows you to get a configured instance of an API object with your user’s token so you can make API calls on behalf of them. Currently Facebook and Twitter are supported out of the box as long as you install the appropriate API library.</p>
    </div>
  </div>
{% endblock %}

templates/profile.html
{% extends '/layouts/boilerplate.html' %}

{% set page_title = "Profile" %}

{% block body_class %}main main-profile{% endblock %}

{% macro show_provider_button(provider_id, display_name, conn, show_update_form=True) %}
  <div class="col-xs-4">
    <h2>{{ display_name }}</h2>
    <hr />
    {% if conn %}
      {% if show_update_form %}
        <form action="{{ url_for('user.social_post', provider_id=provider_id) }}" method="POST" class="post-update">
          <fieldset>
            <div class="form-group">
              <textarea class="form-control input-xlarge" name="message" rows="3">Hello from Flask-Social-Example!</textarea>
            </div>
            <button type="submit" class="btn btn-primary btn-large"><i class="icon-share icon-white"></i> Post Update</button>
          </fieldset>
        </form>
      {% endif %}
      <form action="{{ url_for('social.remove_connection', provider_id=conn.provider_id, provider_user_id=conn.provider_user_id) }}?__METHOD_OVERRIDE__=DELETE" method="POST" role="form" class="remove-connection" style="padding-top: 5px">
        <div class="form_group ">
        	<button type="submit" class="btn btn-danger"><i class="icon-trash icon-white"></i> Remove {{ display_name }} Connection</button>
      	</div>
      </form>
    {% else %}
      <form action="{{ url_for('social.connect', provider_id=provider_id) }}" method="POST" class="create-connection">
        <fieldset>
          <div class="control-group">
            <button type="submit" class="btn btn-success btn-large"><i class="icon-share icon-white"></i> Connect with {{ display_name }}</button>
          </div>
        </fieldset>
      </form>
    {% endif %}
  </div>
{% endmacro %}

{% block layout %}
<div class="page-header">
  <h1>Hello, {{ current_user.email }}!</h1>
</div>
<div class="row">
  {{ show_provider_button('twitter', 'Twitter', twitter_conn) }}
  {{ show_provider_button('facebook', 'Facebook', facebook_conn) }}
</div>
<!--
<div class="row" style="margin-top:50px;">
  {{ show_provider_button('github', 'GitHub', github_conn, False)}}
</div>
-->
{% endblock %}

templates/thanks.html
{% extends '/layouts/boilerplate.html' %}

{% block body_class %}main main-thanks{% endblock %}

{% block layout %}
<h2>Thank You!</h2>

<p>Thanks for registering <strong>{{ user.email }}</strong>! You can now view your <a href="{{ url_for('profile') }}">profile page</a></p>
{% endblock %}